site:
    title: "江矿先森的博客."
    subtitle: "Just be nice, always think twice!"
    limit: 5
    theme: ikuyo
    lang: en
    url: "https://jk.js.org"
    # comment: username
    # logo: "-/images/avatar.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "江矿先森."
        intro: "前(台)端(菜), 喜欢瞎折腾新技术. 乜野都识少少, 先可以扮代表:p"
        avatar: "https://s11.ax1x.com/2024/02/04/pFlmVit.jpg"

build:
    output: "docs"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add .
        git commit -m "update"
        git push origin bl0g
