# Copied files to public folder when build
copy:
    - bundle
    - favicon.png
    - robots.txt
    - CNAME
    - README.md
# I18n Support
lang:
    bg1:
        en: "https://cdn.u1.huluxia.com/g4/M02/93/FA/rBAAdmIXgnOAXsbkAAJqMNDe9LI879.jpg"
        zh: "https://pic6.58cdn.com.cn/nowater/webim/big/n_v212fe49b1d6d5492cb1def84eeff4b142.jpg"
        ru: "https://i0.hdslb.com/bfs/album/6a18c9053f81c4a3316f1ae04452960a19561251.jpg"
        ja: "https://i0.hdslb.com/bfs/album/6a18c9053f81c4a3316f1ae04452960a19561251.jpg"
    bg2:
        en: "https://i0.hdslb.com/bfs/album/1e4ef3774544afc2d9f4f0bbdc34e067bb2e5522.jpg"
        zh: "https://pic4.58cdn.com.cn/nowater/webim/big/n_v2095677bda82c4d5498520d6d164264eb.jpg"
        ru: "https://cdn.u1.huluxia.com/g4/M03/93/EE/rBAAdmIXep-AXyl-AAEgEAtPkYI533.jpg"
        ja: "https://inews.gtimg.com/newsapp_ls/0/12470373728/0"
    bg3:
        en: "https://i0.hdslb.com/bfs/album/69a3bb1bc45d23f6342ed7b63bc831df0e2fd763.jpg"
        zh: "https://pic4.58cdn.com.cn/nowater/webim/big/n_v29423ca287595467a9109489f851551e6.jpg"
        ru: "https://cdn.u1.huluxia.com/g4/M03/93/EE/rBAAdmIXep-AAyWaAAEmufcuuEk301.jpg"
        ja: "https://inews.gtimg.com/newsapp_ls/0/12470381246/0"
    
    archive:
        en: Archive
        zh: 归档
        ru: Архив
        ja: アーカイブ
    tag:
        en: Tag
        zh: 标签
        ru: Теги
        ja: タグ
    rss:
        en: RSS
        zh: 订阅
        ru: RSS
        ja: RSS
    articles:
        en: Articles
        zh: 篇文章
        ru: Записи
        ja: 記事
    updated:
        en: updated
        zh: 更新
        ru: обновлено
        ja: 更新
    prev_page:
        en: Prev
        zh: 上一页
        ru: Назад
        ja: 前のページ
    next_page:
        en: Next
        zh: 下一页
        ru: Далее
        ja: 次のページ
    prev_reading:
        en: Prev Reading
        zh: 上篇文章
        ru: Предыдущая запись
        ja: 新しい記事
    next_reading:
        en: Next Reading
        zh: 下篇文章
        ru: Следующая запись
        ja: 古い記事
    top:
        en: TOP
        zh: 置顶
        ru: Наверх
        ja: TOP
    search:
        en: Search
        zh: 搜索
        ru: Поиск
        ja: 検索
    since_year:
        en: " years ago"
        zh: 年前
        ru: " лет назад"
        ja: 年前
    since_month:
        en: " months ago"
        zh: 个月前
        ru: " месяцев назад"
        ja: ヶ月前
    since_day:
        en: " days ago"
        zh: 天前
        ru: " дней назад"
        ja: 日前
    since_hour:
        en: " hours ago"
        zh: 小时前
        ru: " часов назад"
        ja: 時間前
    since_minute:
        en: " minutes ago"
        zh: 分钟前
        ru: " минут назад"
        ja: 分前
    since_second:
        en: " seconds ago"
        zh: 秒前
        ru: " секунд назад"
        ja: 秒前
